"""fix nullable columns for user

Revision ID: 99675609fd33
Revises: fe7beb89fa5a
Create Date: 2023-11-18 23:14:30.861958

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '99675609fd33'
down_revision = 'fe7beb89fa5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users', 'name',
        existing_type=sa.VARCHAR(length=256),
        nullable=True
    )
    op.alter_column(
        'users', 'surname',
        existing_type=sa.VARCHAR(length=256),
        nullable=True
    )
    op.alter_column(
        'users', 'login',
        existing_type=sa.VARCHAR(length=256),
        nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users', 'login',
        existing_type=sa.VARCHAR(length=256),
        nullable=False
    )
    op.alter_column(
        'users', 'surname',
        existing_type=sa.VARCHAR(length=256),
        nullable=False
    )
    op.alter_column(
        'users', 'name',
        existing_type=sa.VARCHAR(length=256),
        nullable=False
    )
    # ### end Alembic commands ###
